# Survivor Strategy Configuration - with Examples

symbol_initials: "NIFTY25807"

# --- Strike selection ---
# CE: choose OTM strike ABOVE current spot by ce_symbol_gap
# PE: choose OTM strike BELOW current spot by pe_symbol_gap
# Example: If NIFTY = 24,500
#   CE strike = 24,500 + 200 = 24,700 (rounded to 50 step)
#   PE strike = 24,500 - 200 = 24,300 (rounded to 50 step)
ce_symbol_gap: 200
pe_symbol_gap: 200
strike_step: 50

# --- Gap triggers ---
# Example: If CE_ref = 24,500 and NIFTY rises to 24,525
#   delta_up = 25 >= ce_gap(20) → CE buy triggers
# Example: If PE_ref = 24,500 and NIFTY falls to 24,470
#   delta_down = 30 >= pe_gap(20) → PE buy triggers
ce_gap: 20
pe_gap: 20

# --- Reset gaps ---
# Used to reset reference after a reversal
# Example A (CE):
#   CE_ref = 24,500, CE buy triggered at 24,525 → CE_ref updated to 24,525
#   If NIFTY then falls 35 points to 24,490 (>= ce_reset_gap=30)
#   → reset CE_ref = 24,490
# Example B (PE):
#   PE_ref = 24,500, PE buy triggered at 24,470 → PE_ref updated to 24,470
#   If NIFTY then rises 32 points to 24,502 (>= pe_reset_gap=30)
#   → reset PE_ref = 24,502
ce_reset_gap: 30
pe_reset_gap: 30

# --- Quantity and multiplier rules ---
# multiplier = floor(delta / gap)
# Example A: delta = 25, ce_gap = 20 → floor(25/20)=1 → qty = 75×1=75
# Example B: delta = 125, ce_gap = 20 → floor(125/20)=6 → > threshold(5)
#            → trade BLOCKED if cap_action="block", or qty=75×5=375 if "cap"
ce_quantity: 75
pe_quantity: 75
multiplier_formula: "floor(delta / gap)"
buy_multiplier_threshold: 5
multiplier_cap_action: "cap"   # "block" = no trade, "cap" = limit to threshold

# --- Reference points ---
# If start_point=0 → reference starts from current market
# Example: If CE_ref=24,500 and trade triggered at 24,525
#   post_trade_ref_update="set_to_current" → new CE_ref=24,525
ce_start_point: 0
pe_start_point: 0
post_trade_ref_update: "set_to_current"   # or "advance_by_gap"

# --- Trade conditions ---
# Example: If option premium = 12 (< min_price_to_buy=15) → skip trade
min_price_to_buy: 15
check_liquidity: true

# --- Order execution ---
# All trades placed as BUY, MARKET order, NRML product type
order_type: "MARKET"
product_type: "NRML"
trans_type: "BUY"
